### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by hallinen** [MBjoern/arduino-ble-sensiscan#2]
Greetings,
I'm trying to figure out how to have my SHT40 send temp and humidity to the MyAmbiance app.  I did it with my SCD40 and the eps32.  I'm pretty low skill, and so far trying to combine the code for the SHT and  the SCD40 is getting me nowhere.  I thought this library would have a way to do it, but I'm not even getting anything on the serial monitor.
Thanks.
Diane Hallinen

**Comment by psachs** [comment]
This library does not directly connect to MyAmbience. Please check out the Arduino BLE gadget repository and examples if you want to build your own gadget:
https://github.com/Sensirion/arduino-ble-gadget

You can of course also try to combine those libraries but this doesn't really make sense, since if a gadget already advertises data MyAmbience will directly pick it up.

**Comment by MBjoern** [comment]
@hallinen 


Thank you for getting in touch and sorry for the late reply. This library is to sniff out broadcasting gadgets and go-it-yourself gadgets, which publish data with the arduino-ble-gadget library.

As @psachs mentioned, the correct library to communicate with the MyAmbience app and building a do-it-yourself gadget can be found here https://github.com/Sensirion/arduino-ble-gadget

There are also ready to use examples using SHT40 and SCD40 including setup tutorials here: 
https://github.com/Sensirion/arduino-ble-gadget/tree/master/examples/Example8_SCD4x_BLE_Gadget_with_RHT
https://github.com/Sensirion/arduino-ble-gadget/blob/master/documents/SCD4x_BLE_Gadget_Tutorial.md

to combine it with the SHT40 you can use the published SHT40 arduino driver:
https://github.com/Sensirion/info#arduino-drivers-and-examples
https://github.com/Sensirion/arduino-i2c-sht4x

Have fun building great gadgets
